### ISSUE TITLE
metamorph for mcver1.12.2 with mclib

### ISSUE THREAD

**Issue by puvls** [mchorse/blockbuster#100]
pressing B in-game would crash and show this in the launcher.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  McLib core mod (mclib-1.0.3-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 8/31/19 5:48 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:57)
	at net.minecraft.server.management.PlayerProfileCache.func_187319_a(SourceFile:80)
	at net.minecraft.server.management.PlayerProfileCache.func_152655_a(SourceFile:141)
	at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:143)
	at mchorse.vanilla_pack.morphs.PlayerMorph.setProfile(PlayerMorph.java:42)
	at mchorse.vanilla_pack.morphs.PlayerMorph.fromNBT(PlayerMorph.java:216)
	at mchorse.vanilla_pack.PlayerMorphFactory.getMorphs(PlayerMorphFactory.java:73)
	at mchorse.metamorph.api.MorphManager.getMorphs(MorphManager.java:248)
	at mchorse.metamorph.client.gui.elements.GuiCreativeMorphs.compileCategories(GuiCreativeMorphs.java:270)
	at mchorse.metamorph.client.gui.elements.GuiCreativeMorphs.<init>(GuiCreativeMorphs.java:133)
	at mchorse.metamorph.client.gui.GuiCreativeMenu.func_73866_w_(GuiCreativeMenu.java:84)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at mchorse.metamorph.client.KeyboardHandler.onKey(KeyboardHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_KeyboardHandler_onKey_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2017)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:32)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:57)
	at net.minecraft.server.management.PlayerProfileCache.func_187319_a(SourceFile:80)
	at net.minecraft.server.management.PlayerProfileCache.func_152655_a(SourceFile:141)
	at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:143)
	at mchorse.vanilla_pack.morphs.PlayerMorph.setProfile(PlayerMorph.java:42)
	at mchorse.vanilla_pack.morphs.PlayerMorph.fromNBT(PlayerMorph.java:216)
	at mchorse.vanilla_pack.PlayerMorphFactory.getMorphs(PlayerMorphFactory.java:73)
	at mchorse.metamorph.api.MorphManager.getMorphs(MorphManager.java:248)
	at mchorse.metamorph.client.gui.elements.GuiCreativeMorphs.compileCategories(GuiCreativeMorphs.java:270)
	at mchorse.metamorph.client.gui.elements.GuiCreativeMorphs.<init>(GuiCreativeMorphs.java:133)
	at mchorse.metamorph.client.gui.GuiCreativeMenu.func_73866_w_(GuiCreativeMenu.java:84)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at mchorse.metamorph.client.KeyboardHandler.onKey(KeyboardHandler.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_KeyboardHandler_onKey_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2017)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['EffectedLizard1'/340, l='MpServer', x=26.13, y=64.00, z=249.97]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (12,64,240), Chunk: (at 12,4,0 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1212 game time, 1212 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 85 total; [EntityZombie['Zombie'/128, l='MpServer', x=-17.53, y=20.00, z=321.71], EntityZombie['Zombie'/129, l='MpServer', x=-16.50, y=20.00, z=327.25], EntityPig['Pig'/130, l='MpServer', x=-28.77, y=69.00, z=325.82], EntityPig['Pig'/131, l='MpServer', x=-28.90, y=69.00, z=327.55], EntityPig['Pig'/132, l='MpServer', x=-27.36, y=69.00, z=327.01], EntitySkeleton['Skeleton'/159, l='MpServer', x=-3.29, y=20.00, z=206.51], EntitySkeleton['Skeleton'/160, l='MpServer', x=-7.16, y=23.00, z=220.44], EntitySkeleton['Skeleton'/161, l='MpServer', x=-12.31, y=24.00, z=222.51], EntityBat['Bat'/162, l='MpServer', x=10.33, y=14.13, z=219.71], EntityCreeper['Creeper'/163, l='MpServer', x=-10.50, y=46.00, z=222.50], EntityZombie['Zombie'/164, l='MpServer', x=-1.70, y=36.00, z=254.05], EntityCreeper['Creeper'/165, l='MpServer', x=-1.16, y=37.00, z=252.83], EntitySkeleton['Skeleton'/166, l='MpServer', x=-2.50, y=15.00, z=263.50], EntityBat['Bat'/167, l='MpServer', x=1.58, y=35.18, z=255.01], EntityBat['Bat'/168, l='MpServer', x=-15.25, y=54.10, z=274.58], EntityChicken['Chicken'/169, l='MpServer', x=-14.50, y=65.00, z=318.50], EntityChicken['Chicken'/170, l='MpServer', x=-7.57, y=64.00, z=320.19], EntityCreeper['Creeper'/556, l='MpServer', x=-34.50, y=18.00, z=170.50], EntitySkeleton['Skeleton'/557, l='MpServer', x=-2.50, y=13.00, z=238.50], EntitySkeleton['Skeleton'/181, l='MpServer', x=1.50, y=25.00, z=212.50], EntityBat['Bat'/182, l='MpServer', x=12.95, y=11.79, z=221.50], EntityCreeper['Creeper'/183, l='MpServer', x=2.50, y=19.00, z=243.50], EntityBat['Bat'/184, l='MpServer', x=7.75, y=30.10, z=247.25], EntityZombie['Zombie'/440, l='MpServer', x=104.50, y=61.00, z=242.50], EntitySkeleton['Skeleton'/185, l='MpServer', x=5.50, y=33.00, z=245.07], EntityChicken['Chicken'/186, l='MpServer', x=-6.12, y=64.00, z=267.64], EntityChicken['Chicken'/187, l='MpServer', x=15.12, y=65.00, z=264.65], EntityChicken['Chicken'/188, l='MpServer', x=6.82, y=65.00, z=247.58], EntityChicken['Chicken'/189, l='MpServer', x=14.40, y=65.00, z=260.86], EntityChicken['Chicken'/190, l='MpServer', x=5.46, y=64.00, z=282.84], EntityChicken['Chicken'/191, l='MpServer', x=2.50, y=63.00, z=292.50], EntityChicken['Chicken'/192, l='MpServer', x=4.34, y=64.00, z=289.11], EntityChicken['Chicken'/193, l='MpServer', x=1.50, y=64.00, z=289.50], EntitySkeleton['Skeleton'/198, l='MpServer', x=23.50, y=33.00, z=271.50], EntityItem['item.item.seeds'/199, l='MpServer', x=26.07, y=62.00, z=301.56], EntityItem['item.item.seeds'/200, l='MpServer', x=28.87, y=65.00, z=299.51], EntityBat['Bat'/202, l='MpServer', x=44.41, y=27.81, z=317.22], EntityPig['Pig'/204, l='MpServer', x=61.50, y=72.00, z=311.50], EntityChicken['Chicken'/205, l='MpServer', x=56.54, y=71.00, z=319.64], EntityChicken['Chicken'/206, l='MpServer', x=57.21, y=71.00, z=318.48], EntityChicken['Chicken'/207, l='MpServer', x=52.48, y=69.00, z=322.89], EntityChicken['Chicken'/208, l='MpServer', x=54.50, y=70.00, z=324.50], EntityEnderman['Enderman'/81, l='MpServer', x=-53.50, y=28.00, z=185.50], EntitySkeleton['Skeleton'/209, l='MpServer', x=67.59, y=38.00, z=304.50], EntityPig['Pig'/210, l='MpServer', x=65.50, y=72.00, z=308.50], EntityPig['Pig'/211, l='MpServer', x=63.60, y=72.00, z=311.04], EntityCreeper['Creeper'/84, l='MpServer', x=-53.87, y=34.00, z=230.62], EntityPig['Pig'/212, l='MpServer', x=64.50, y=72.00, z=307.68], EntityBat['Bat'/213, l='MpServer', x=67.75, y=41.00, z=328.25], EntitySkeleton['Skeleton'/220, l='MpServer', x=83.50, y=47.00, z=177.50], EntityEnderman['Enderman'/221, l='MpServer', x=85.50, y=39.00, z=188.50], EntitySkeleton['Skeleton'/222, l='MpServer', x=81.50, y=48.00, z=190.50], EntityZombie['Zombie'/95, l='MpServer', x=-33.50, y=24.00, z=185.50], EntityZombie['Zombie'/223, l='MpServer', x=86.57, y=49.00, z=202.50], EntityBat['Bat'/96, l='MpServer', x=-25.72, y=21.02, z=178.33], EntityCreeper['Creeper'/224, l='MpServer', x=80.54, y=33.00, z=215.19], EntityBat['Bat'/97, l='MpServer', x=-20.45, y=24.19, z=174.09], EntityZombie['Zombie'/225, l='MpServer', x=95.50, y=37.00, z=225.50], EntityCreeper['Creeper'/98, l='MpServer', x=-38.50, y=38.00, z=178.50], EntityZombie['Zombie'/226, l='MpServer', x=91.50, y=19.00, z=255.50], EntitySkeleton['Skeleton'/99, l='MpServer', x=-37.50, y=38.00, z=178.50], EntitySkeleton['Skeleton'/227, l='MpServer', x=87.50, y=37.00, z=249.50], EntityPlayerSP['EffectedLizard1'/340, l='MpServer', x=26.13, y=64.00, z=249.97], EntityBat['Bat'/100, l='MpServer', x=-42.60, y=57.53, z=207.52], EntitySkeleton['Skeleton'/228, l='MpServer', x=93.28, y=41.00, z=248.48], EntitySkeleton['Skeleton'/229, l='MpServer', x=93.50, y=40.00, z=244.79], EntityZombie['Zombie'/230, l='MpServer', x=91.27, y=20.00, z=257.46], EntityChicken['Chicken'/231, l='MpServer', x=84.80, y=72.00, z=261.69], EntityChicken['Chicken'/232, l='MpServer', x=86.50, y=73.00, z=262.50], EntityChicken['Chicken'/233, l='MpServer', x=81.83, y=68.00, z=257.55], EntityChicken['Chicken'/234, l='MpServer', x=81.50, y=72.00, z=263.50], EntityZombie['Zombie'/235, l='MpServer', x=92.78, y=59.00, z=300.49], EntityCreeper['Creeper'/117, l='MpServer', x=-19.50, y=17.00, z=174.50], EntityBat['Bat'/118, l='MpServer', x=-35.56, y=12.93, z=180.27], EntityCreeper['Creeper'/248, l='MpServer', x=88.84, y=32.00, z=199.50], EntitySkeleton['Skeleton'/504, l='MpServer', x=85.50, y=40.00, z=240.50], EntityCreeper['Creeper'/249, l='MpServer', x=99.50, y=29.00, z=199.50], EntityZombie['Zombie'/122, l='MpServer', x=-20.50, y=17.00, z=176.50], EntitySpider['Spider'/250, l='MpServer', x=98.50, y=29.00, z=198.50], EntityBat['Bat'/123, l='MpServer', x=-16.45, y=40.04, z=224.75], EntityCreeper['Creeper'/251, l='MpServer', x=98.97, y=31.00, z=224.63], EntityBat['Bat'/124, l='MpServer', x=-17.26, y=48.35, z=270.49], EntityZombie['Zombie'/125, l='MpServer', x=-17.50, y=20.00, z=318.50], EntityChicken['Chicken'/126, l='MpServer', x=-12.71, y=65.00, z=326.16], EntityChicken['Chicken'/127, l='MpServer', x=-18.21, y=66.00, z=317.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at info.mineshafter.GameStarter.main(GameStarter.java:32)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 184141328 bytes (175 MB) / 521011200 bytes (496 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 8 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                        | Signature                                |
	|:------ |:---------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge      | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mclib      | 1.0.3        | mclib-1.0.3-1.12.2.jar        | None                                     |
	| LCHIJA | metamorph  | 1.1.8        | metamorph-1.1.8-1.12.2.jar    | None                                     |
	| LCHIJA | emoticons  | 0.3          | emoticons-0.3-1.12.2-dist.jar | None                                     |
	| UD     | mclib_core | 1.0.3        | minecraft.jar                 | None                                     |

	Loaded coremods (and transformers): 
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4973' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz`
the only way to dont do this is to press N.

**Comment by mchorse** [comment]
Wrong repository. This Blockbuster's, not [Metamorph's](https://github.com/mchorse/metamorph) repo. 

Does it happens when you have internet or not?
