### ISSUE TITLE
Crash on server start [1.3-pre]

### ISSUE THREAD

**Issue by Lightwave413** [mchorse/blockbuster#12]
Although the mod works in Singleplayer and LAN, loading it into a server crashes every time.
Crash Report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 9/15/16 11:43 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:589)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:92)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:147)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:140)
	at mchorse.blockbuster.network.Dispatcher.register(Dispatcher.java:147)
	at mchorse.blockbuster.network.Dispatcher.register(Dispatcher.java:108)
	at mchorse.blockbuster.CommonProxy.preLoad(CommonProxy.java:43)
	at mchorse.blockbuster.Blockbuster.registerAllItemsBlocksAndEntities(Blockbuster.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@62ef27a8 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.RuntimeException: Attempted to load class bmr for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:49)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1209275144 bytes (1153 MB) / 1365245952 bytes (1302 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx2048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.2051 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.2051-universal.jar) 
	UCH	Forge{12.17.0.2051} [Minecraft Forge] (forge-1.9.4-12.17.0.2051-universal.jar) 
	UCE	blockbuster{1.3-pre} [Blockbuster] (blockbuster-1.3-pre.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Lightwave413** [comment]
sorry, I typed the title in haste

**Comment by mchorse** [comment]
Nice to see you again :)

> Although the mod works in Singleplayer and LAN, loading it into a server crashes every time.

I actually fixed it in a commit after pre-release, if you'll check out the `dev` branch, and build mod manually, you should have working mod on dedicated server.

I didn't really tested much stuff on dedicated server, so it would be apreciated if you could give me a feedback on how it does on the server. Thanks :)

**Comment by mchorse** [comment]
@Lightwave413, any updates? Is it working for you if you'll build with a more recent `dev` commit?

**Comment by Lightwave413** [comment]
Took me a little while to remember how to make it build properly (Gradle & UTF-8 issues).
It appears to be working fine, so I'll close this issue now.

**Comment by mchorse** [comment]
Ok, thank you for feedback :)
