### ISSUE TITLE
Game Crash 1.12.2

### ISSUE THREAD

**Issue by 0hpsychox** [mchorse/blockbuster#121]
soo im trying to add in my 3d models and when I try to load minecraft with blockbuster (1.6.2) Mclib for 1.12.2 and metamorph 1.12.2 my game starts to load and it goes into minecraft and crashes. It happends with every version of blockbuster I use and if I take blockbuster out minecraft works perfectly any help?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
  McLib core mod (mclib-1.0.4-1.12.2 (2).jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/31/20 7:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster)
Caused by: java.lang.IllegalAccessError: tried to access field mchorse.mclib.utils.files.GlobalTree.trees from class mchorse.blockbuster.ClientProxy
	at mchorse.blockbuster.ClientProxy.injectResourcePack(ClientProxy.java:176)
	at mchorse.blockbuster.ClientProxy.preLoad(ClientProxy.java:140)
	at mchorse.blockbuster.Blockbuster.preLoad(Blockbuster.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 735851456 bytes (701 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 9 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version      | Source                          | Signature                                |
	|:----- |:---------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| LCH   | minecraft        | 1.12.2       | minecraft.jar                   | None                                     |
	| LCH   | mcp              | 9.42         | minecraft.jar                   | None                                     |
	| LCH   | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge            | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | mclib            | 1.0.4        | mclib-1.0.4-1.12.2 (2).jar      | None                                     |
	| LCH   | metamorph        | 1.1.10       | metamorph-1.1.10-1.12.2 (1).jar | None                                     |
	| LCE   | blockbuster      | 1.6.1        | blockbuster-1.6.1-1.12.2.jar    | None                                     |
	| UD    | blockbuster_core | 1.6.1        | minecraft.jar                   | None                                     |
	| UD    | mclib_core       | 1.0.4        | minecraft.jar                   | None                                     |

	Loaded coremods (and transformers): 
BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
McLib core mod (mclib-1.0.4-1.12.2 (2).jar)
  mchorse.mclib.core.McLibCMClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8794' Renderer: 'ATI Mobility Radeon HD 4200 '

**Comment by mchorse** [comment]
You need Blockbuster 1.6.2 for McLib 1.0.4. So either update Blockbuster, or downgrade McLib to 1.0.3.
