### ISSUE TITLE
Blockbuster crashing on startup

### ISSUE THREAD

**Issue by QuiteDouble** [mchorse/blockbuster#146]
Here's my log
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.6-1.12.2.jar)
  CamPatchingLoader (CMDCam_v1.4.10_mc1.12.2.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  McLib core mod (mclib-2.0.2-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.20_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  BlockbusterCore (blockbuster-2.0.2-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/16/20 4:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster)
Caused by: java.lang.NoClassDefFoundError: mchorse/aperture/events/CameraEditorEvent$Rewind
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at mchorse.blockbuster.aperture.CameraHandler.registerHandlers(CameraHandler.java:110)
	at mchorse.blockbuster.aperture.CameraHandler.register(CameraHandler.java:103)
	at mchorse.blockbuster.ClientProxy.load(ClientProxy.java:199)
	at mchorse.blockbuster.Blockbuster.load(Blockbuster.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mchorse.aperture.events.CameraEditorEvent$Rewind
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 903080440 bytes (861 MB) / 3388997632 bytes (3232 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 47 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                   | Signature                                |
	|:----- |:--------------------- |:----------------- |:---------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft             | 1.12.2            | minecraft.jar                            | None                                     |
	| LCHI  | mcp                   | 9.42              | minecraft.jar                            | None                                     |
	| LCHI  | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar            | None                                     |
	| LCHI  | forge                 | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar            | None                                     |
	| LCHI  | creativecoredummy     | 1.0.0             | minecraft.jar                            | None                                     |
	| LCHI  | obfuscate             | 0.4.2             | minecraft.jar                            | None                                     |
	| LCHI  | techguns_core         | 1.12.2-1.0        | minecraft.jar                            | None                                     |
	| LCHI  | ebwizardry            | 4.2.11            | ElectroblobsWizardry-4.2.11-MC1.12.2.jar | None                                     |
	| LCHI  | ancientspellcraft     | 1.0.2             | AncientSpellcraft-1.0.2.jar              | None                                     |
	| LCHI  | mclib                 | 2.0.2             | mclib-2.0.2-1.12.2.jar                   | None                                     |
	| LCHI  | aperture              | 1.3.6             | aperture-1.3.6-1.12.2.jar                | None                                     |
	| LCHI  | arcane_essentials     | 1.0               | Arcane+Essentials-1.0.0-alpha-6.jar      | None                                     |
	| LCHI  | gorecore              | 1.12.2-0.4.5      | avatarmod-1.5.17-alpha.jar               | None                                     |
	| LCHI  | avatarmod             | 1.5.17-alpha      | avatarmod-1.5.17-alpha.jar               | None                                     |
	| LCHI  | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                   | None                                     |
	| LCHI  | moreplayermodels      | 1.12.2            | MorePlayerModels_1.12.2-(05Dec19).jar    | None                                     |
	| LCHI  | metamorph             | 1.2.2             | metamorph-1.2.2-1.12.2.jar               | None                                     |
	| LCHE  | blockbuster           | 2.0.2             | blockbuster-2.0.2-1.12.2.jar             | None                                     |
	| LCH   | ctm                   | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                | None                                     |
	| LCH   | chisel                | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar             | None                                     |
	| LCH   | chiselsandbits        | 14.33             | chiselsandbits-14.33.jar                 | None                                     |
	| LCH   | creativecore          | 1.10.0            | CreativeCore_v1.10.20_mc1.12.2.jar       | None                                     |
	| LCH   | cmdcam                | 1.4.0             | CMDCam_v1.4.10_mc1.12.2.jar              | None                                     |
	| LCH   | cosmeticarmorreworked | 1.12.2-v5a        | CosmeticArmorReworked-1.12.2-v5a.jar     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | customnpcs            | 1.12              | CustomNPCs_1.12.2-(05Jul20).jar          | None                                     |
	| LCH   | ptrmodellib           | 1.0.4             | PTRLib-1.0.4.jar                         | None                                     |
	| LCH   | props                 | 2.6.3             | Decocraft-2.6.3_1.12.2.jar               | None                                     |
	| LCH   | rcraft                | 2.1.8             | dotHack+Weapons-2.1.8.jar                | None                                     |
	| LCH   | emoticons             | 0.5               | emoticons-0.5-1.12.2-dist.jar            | None                                     |
	| LCH   | extra_spells          | 1.1.4             | ExtraSpells-1.12.2-1.1.4.jar             | None                                     |
	| LCH   | cfm                   | 6.3.1             | furniture-6.3.1-1.12.2.jar               | None                                     |
	| LCH   | ghostspells           | 0.6-alpha         | Ghostspells-0.6-alpha.jar                | None                                     |
	| LCH   | journeymap            | 1.12.2-5.5.4      | journeymap-1.12.2-5.5.4.jar              | None                                     |
	| LCH   | opframe               | 1.4.0             | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar  | None                                     |
	| LCH   | tails                 | 1.12-1.10.0       | Tails-1.12-1.10.0.jar                    | None                                     |
	| LCH   | techguns              | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar       | None                                     |
	| LCH   | variedcommodities     | 1.12.2            | VariedCommodities_1.12.2(21nov19).jar    | None                                     |
	| LCH   | vehicle               | 0.44.1            | vehicle-mod-0.44.1-1.12.2.jar            | None                                     |
	| LCH   | wearablebackpacks     | 3.1.4             | WearableBackpacks-1.12.2-3.1.4.jar       | None                                     |
	| LCH   | llibrary              | 1.7.19            | llibrary-1.7.19-1.12.2.jar               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | wings                 | 1.1.6             | wings-1.1.6-1.12.2.jar                   | None                                     |
	| LCH   | bauble_wings          | 1.0.0             | wings-1.1.6-1.12.2.jar                   | None                                     |
	| LCH   | worldedit             | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| UD    | blockbuster_core      | 2.0.2             | minecraft.jar                            | None                                     |
	| UD    | mclib_core            | 2.0.2             | minecraft.jar                            | None                                     |
	| UD    | mowzies_wings         | 1.0.0             | wings-1.1.6-1.12.2.jar                   | None                                     |
	| UD    | mobends_wings         | 1.0.0             | wings-1.1.6-1.12.2.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
CamPatchingLoader (CMDCam_v1.4.10_mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
McLib core mod (mclib-2.0.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.20_mc1.12.2.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BlockbusterCore (blockbuster-2.0.2-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13596 Compatibility Profile Context 20.5.1 27.20.1017.1011' Renderer: 'AMD Radeon(TM) RX 560 Series'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13596 Compatibility Profile Context 20.5.1 27.20.1017.1011
	OpenGlRenderer: AMD Radeon(TM) RX 560 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by mchorse** [comment]
Update your Aperture to the latest version.
