### ISSUE TITLE
Blockbuster crash on gif skins.

### ISSUE THREAD

**Issue by NEWMattiou** [mchorse/blockbuster#230]
My blockbuster (newer version) crashs when I put a gif skin on my skin.
There is the crash report : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShaderHookLoader (Minema-3.7.1-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  BlockbusterCore (blockbuster-2.5-1.12.2.jar)
  FutureMC (future-mc-0.2.11.jar)
  APCoreMod (aperture-1.8-1.12.2.jar)
  McLib core mod (mclib-2.4-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 10/10/22 10:42 AM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 1
	at mchorse.blockbuster.client.textures.GifTexture.getFrame(GifTexture.java:116)
	at mchorse.blockbuster.client.textures.GifTexture.func_110552_b(GifTexture.java:82)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:75)
	at mchorse.blockbuster.client.render.RenderCustomModel.bindLastTexture(RenderCustomModel.java:58)
	at mchorse.blockbuster.client.render.RenderCustomModel.bindLastTexture(RenderCustomModel.java:51)
	at mchorse.blockbuster.client.gui.dashboard.panels.model_editor.utils.GuiBBModelRenderer.drawUserModel(GuiBBModelRenderer.java:172)
	at mchorse.mclib.client.gui.framework.elements.GuiModelRenderer.drawModel(GuiModelRenderer.java:334)
	at mchorse.mclib.client.gui.framework.elements.GuiModelRenderer.draw(GuiModelRenderer.java:259)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.mclib.client.gui.framework.elements.GuiDelegateElement.draw(GuiDelegateElement.java:161)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.metamorph.client.gui.creative.GuiCreativeMorphsList.draw(GuiCreativeMorphsList.java:651)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.mclib.client.gui.framework.GuiBase.func_73863_a(GuiBase.java:199)
	at mchorse.metamorph.client.gui.creative.GuiCreativeScreen.func_73863_a(GuiCreativeScreen.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mchorse.blockbuster.client.textures.GifTexture.getFrame(GifTexture.java:116)
	at mchorse.blockbuster.client.textures.GifTexture.func_110552_b(GifTexture.java:82)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:75)
	at mchorse.blockbuster.client.render.RenderCustomModel.bindLastTexture(RenderCustomModel.java:58)
	at mchorse.blockbuster.client.render.RenderCustomModel.bindLastTexture(RenderCustomModel.java:51)
	at mchorse.blockbuster.client.gui.dashboard.panels.model_editor.utils.GuiBBModelRenderer.drawUserModel(GuiBBModelRenderer.java:172)
	at mchorse.mclib.client.gui.framework.elements.GuiModelRenderer.drawModel(GuiModelRenderer.java:334)
	at mchorse.mclib.client.gui.framework.elements.GuiModelRenderer.draw(GuiModelRenderer.java:259)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.mclib.client.gui.framework.elements.GuiDelegateElement.draw(GuiDelegateElement.java:161)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.metamorph.client.gui.creative.GuiCreativeMorphsList.draw(GuiCreativeMorphsList.java:651)
	at mchorse.mclib.client.gui.framework.elements.GuiElements.draw(GuiElements.java:211)
	at mchorse.mclib.client.gui.framework.elements.GuiElement.draw(GuiElement.java:728)
	at mchorse.mclib.client.gui.framework.GuiBase.func_73863_a(GuiBase.java:199)
	at mchorse.metamorph.client.gui.creative.GuiCreativeScreen.func_73863_a(GuiCreativeScreen.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: mchorse.metamorph.client.gui.creative.GuiCreativeScreen
	Mouse location: Scaled: (72, 160). Absolute: (145, 688)
	Screen size: Scaled: (960, 505). Absolute: (1920, 1009). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['NEWMattiou'/36, l='MpServer', x=33.57, y=66.00, z=76.24]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,98,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 457791680 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['NEWMattiou'/36, l='MpServer', x=33.57, y=66.00, z=76.24]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 423129200 bytes (403 MB) / 905969664 bytes (864 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 17 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID               | Version      | Source                                   | Signature                                |
	|:------ |:---------------- |:------------ |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft        | 1.12.2       | minecraft.jar                            | None                                     |
	| LCHIJA | mcp              | 9.42         | minecraft.jar                            | None                                     |
	| LCHIJA | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge            | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mclib            | 2.4          | mclib-2.4-1.12.2.jar                     | None                                     |
	| LCHIJA | metamorph        | 1.3          | metamorph-1.3-1.12.2.jar                 | None                                     |
	| LCHIJA | minema           | 3.7.1        | Minema-3.7.1-1.12.2.jar                  | None                                     |
	| LCHIJA | blockbuster      | 2.5          | blockbuster-2.5-1.12.2.jar               | None                                     |
	| LCHIJA | aperture         | 1.8          | aperture-1.8-1.12.2.jar                  | None                                     |
	| LCHIJA | forgelin         | 1.8.4        | Forgelin-1.8.4.jar                       | None                                     |
	| LCHIJA | fw               | 1.6.0        | FullscreenWindowed-1.12-1.6.0.jar        | None                                     |
	| LCHIJA | futuremc         | 0.2.6        | future-mc-0.2.11.jar                     | None                                     |
	| LCHIJA | palamod          | 2.6          | Palamods+(1.12.2)+V2.5.jar               | None                                     |
	| LCHIJA | worldedit        | 6.1.10       | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |
	| UD     | aperture_core    | 1.8          | minecraft.jar                            | None                                     |
	| UD     | blockbuster_core | 2.5          | minecraft.jar                            | None                                     |
	| UD     | mclib_core       | 2.4          | minecraft.jar                            | None                                     |

	Loaded coremods (and transformers): 
ShaderHookLoader (Minema-3.7.1-1.12.2.jar)
  info.ata4.minecraft.minema.shaderHook_coremod.ShaderHookInjector
ForgelinPlugin (Forgelin-1.8.4.jar)
  
BlockbusterCore (blockbuster-2.5-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
APCoreMod (aperture-1.8-1.12.2.jar)
  mchorse.aperture.core.APCoreClassTransformer
McLib core mod (mclib-2.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.100.9864' Renderer: 'Intel(R) UHD Graphics'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.100.9864, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Jylio Default §l§e[V&P] 1.12.2.zip, iron-golem-to-warden-1-16-3-optifine-request.zip (incompatible), Zombie+Pigman+to+Zombified+Piglins+1.12.zip, !     §2§lBetter §b§lCr§f§laft§c§lok §av§21.0§8.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9864
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Chryfi** [comment]
Fixed
