### ISSUE TITLE
Blockbuster crashing on startup

### ISSUE THREAD

**Issue by useratia2** [mchorse/blockbuster#236]
---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  McLib core mod (mclib-2.4.1-1.12.2.jar)
  BlockbusterCore (blockbuster-1.5.3-1.12.2.jar)
  APCoreMod (aperture-1.8.1-1.12.2.jar)
Contact their authors BEFORE contacting forge
 
// Shall we play a game?
 
Time: 1/13/23 2:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster)
Caused by: java.lang.NoClassDefFoundError: mchorse/blockbuster/client/gui/dashboard/panels/model_block/GuiModelBlockPanel
	at mchorse.blockbuster.common.CommonProxy.preLoad(CommonProxy.java:94)
	at mchorse.blockbuster.common.ClientProxy.preLoad(ClientProxy.java:94)
	at mchorse.blockbuster.Blockbuster.preLoad(Blockbuster.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mchorse.blockbuster.client.gui.dashboard.panels.model_block.GuiModelBlockPanel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: mchorse/mclib/client/gui/widgets/GuiInventory$IInventoryPicker
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more
Caused by: java.lang.ClassNotFoundException: mchorse.mclib.client.gui.widgets.GuiInventory$IInventoryPicker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 51 more
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1807521976 bytes (1723 MB) / 2130051072 bytes (2031 MB) up to 3203792896 bytes (3055 MB)
	JVM Flags: 10 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:ConcGCThreads=1 -Xms2048M -Xmx3072M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 18 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 
	| State | ID                | Version         | Source                               | Signature                                |
	|:----- |:----------------- |:--------------- |:------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2          | minecraft.jar                        | None                                     |
	| LCH   | mcp               | 9.42            | minecraft.jar                        | None                                     |
	| LCH   | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2860    | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | mclib             | 2.4.1           | mclib-2.4.1-1.12.2.jar               | None                                     |
	| LCH   | aperture          | 1.8.1           | aperture-1.8.1-1.12.2.jar            | None                                     |
	| LCH   | metamorph         | 1.3.1           | Metamorph-1.3.1-1.12.2.jar           | None                                     |
	| LCE   | blockbuster       | 1.5.3           | blockbuster-1.5.3-1.12.2.jar         | None                                     |
	| LC    | chiselsandbits    | 14.32           | chiselsandbits_1.12.2_14.32.jar      | None                                     |
	| LC    | customnpcs        | 1.12            | CustomNPCs_1.12.2_05Jul20.jar        | None                                     |
	| LC    | ptrmodellib       | 1.0.5           | PTRLib-1.0.5.jar                     | None                                     |
	| LC    | props             | 2.6.3.7         | Decocraft-2.6.3.7_1.12.2.jar         | None                                     |
	| LC    | cfm               | 6.3.0           | Furniture-Mod-6.3.2-1.12.2.jar       | None                                     |
	| LC    | ism               | 2.6.1 MC-1.12.2 | ism-2.6.1 MC-1.12.2.jar              | None                                     |
	| LC    | variedcommodities | 1.12.2          | VariedCommodities_1.12.2-13Jan22.jar | None                                     |
	| UD    | aperture_core     | 1.8.1           | minecraft.jar                        | None                                     |
	| UD    | blockbuster_core  | @VERSION@       | minecraft.jar                        | None                                     |
	| UD    | mclib_core        | 2.4.1           | minecraft.jar                        | None                                     |
 
	Loaded coremods (and transformers): 
McLib core mod (mclib-2.4.1-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
BlockbusterCore (blockbuster-1.5.3-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
APCoreMod (aperture-1.8.1-1.12.2.jar)
  mchorse.aperture.core.APCoreClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 610/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.35
	OpenGlRenderer: GeForce GT 610/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Chryfi** [comment]
You are using BB 1.5.3 with newer versions of mclib, aperture etc. These are not compatible. Upgrade BB to the newest version of 2.6.

**Comment by useratia2** [comment]
> You are using BB 1.5.3 with newer versions of mclib, aperture etc. These are not compatible. Upgrade BB to the newest version of 2.6.

i cant use blockbuster version 1.6+ because of a bug with actors shooting at each other from bb gun

**Comment by Chryfi** [comment]
Did you even try if it was fixed in the newer versions? Try Blockbuster before BB 2.4 because in 2.4 some bugs were introduced by another person or try BB 2.6 which has fixes to most bugs. BB 1.6 is ancient. If you want to stay on a years old blockbuster version, you have to downgrade all your mods like mclib, metamorph and aperture.
