### ISSUE TITLE
Start-Up occurring with new Aperture Update

### ISSUE THREAD

**Issue by IsDerpy** [mchorse/blockbuster#73]
Crashes on Start-Up on forge boot-up screen.

**Version:**  Forge - 1.12.2 - 14.23.5.2768
**Mods:**
-Aperture-1.2-1.12.2
-Blockbuster-1.5.2-1.12.2
-Mclib-1.0-1.12.2
-Metamorph-1.1.6-1.12.2

**Crash Report:**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BlockbusterCore (blockbuster-1.5.2-1.12.2.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/24/18 2:06 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Blockbuster (blockbuster)
Caused by: java.lang.NoClassDefFoundError: mchorse/aperture/events/CameraEditorScrubbedEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at mchorse.blockbuster.aperture.CameraHandler.register(CameraHandler.java:73)
	at mchorse.blockbuster.common.ClientProxy.load(ClientProxy.java:190)
	at mchorse.blockbuster.Blockbuster.load(Blockbuster.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mchorse.aperture.events.CameraEditorScrubbedEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 463532928 bytes (442 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 10 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version      | Source                          | Signature                                |
	|:----- |:---------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft        | 1.12.2       | minecraft.jar                   | None                                     |
	| UCHI  | mcp              | 9.42         | minecraft.jar                   | None                                     |
	| UCHI  | FML              | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge            | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | ambientsounds    | 2.0.0        | AmbientSounds_v2.3_mc1.12.2.jar | None                                     |
	| UCHI  | mclib            | 1.0          | mclib-1.0-1.12.2 (1).jar        | None                                     |
	| UCHI  | aperture         | 1.2          | aperture-1.2-1.12.2.jar         | None                                     |
	| UCHI  | metamorph        | 1.1.6        | metamorph-1.1.6-1.12.2.jar      | None                                     |
	| UCHEE | blockbuster      | 1.5.2        | blockbuster-1.5.2-1.12.2.jar    | None                                     |
	| UD    | blockbuster_core | 1.5.2        | minecraft.jar                   | None                                     |

	Loaded coremods (and transformers): 
BlockbusterCore (blockbuster-1.5.2-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.5018' Renderer: 'Intel(R) HD Graphics 520'

**Comment by mchorse** [comment]
That was a mistake releasing Aperture before Blockbuster 🤦‍♂️ 

Here are dev builds of [Blockbuster](https://cdn.discordapp.com/attachments/427869402424410112/526144543540772865/blockbuster-1.5.3-1.12.2.jar) and [Metamorph](https://cdn.discordapp.com/attachments/427869402424410112/526144538260144169/metamorph-1.1.7-1.12.2.jar) for now. I plan to release both tomorrow (or in worst case, at 26th).
